### ISSUE TITLE
"fieldProps" passed from "connectField" duplicate known props

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-conform#8]
## What
`fieldProps` passed to the custom styled inputs contain the props which are already in the WrappedComponent's `this.props`. This creates the duplicates and makes props tree hard to read.

## Expected behavior
* Think of an efficient way how to handle this. Diff props?

**Comment by Vidlec** [comment]
What about having just this.props. No fieldProps. Or the other way around. Is this viable?

**Comment by kettanaito** [comment]
Implemented #21. Closing.
